name: Copy Docs to Dest Repo

on:
  push:
    branches:
      - main # Trigger the workflow on push to the main branch

jobs:
  copy-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repo
        id: source
        uses: actions/checkout@v4
        with:
          path: source-repo

      - name: Get Source Commit Hash
        id: get-source-hash
        run: echo "::set-output name=hash::$(git -C source-repo rev-parse --short HEAD)"

      - name: Checkout Dest Repo
        uses: actions/checkout@v4
        with:
          repository: "calvinbrewer/dest-repo"
          path: dest-repo
          ssh-key: ${{ secrets.DEST_REPO_ACCESS_TOKEN }}
          fetch-depth: 0 # Necessary for pushing commits

      - name: Copy Docs
        run: |
          rm -rf dest-repo/src/app/docs
          mkdir -p dest-repo/src/app
          cp -r source-repo/docs dest-repo/src/app

      - name: Check for Changes
        id: check-changes
        run: |
          cd dest-repo
          git add src/app/docs
          if git diff --cached --quiet; then
            echo "::set-output name=changes::false"
          else
            echo "::set-output name=changes::true"
          fi

      - name: Commit Changes
        if: steps.check-changes.outputs.changes == 'true'
        run: |
          cd dest-repo
          git config --global user.name 'github-actions-sync-docs[bot]'
          git config --global user.email 'github-actions-sync-docs[bot]@users.noreply.github.com'
          git commit -m "Update docs from source repo at commit ${{ steps.get-source-hash.outputs.hash }}"

      - name: Push Changes
        if: steps.check-changes.outputs.changes == 'true'
        run: |
          cd dest-repo
          git push origin main
